add background color for browser does not support gradient
mowzz/forum pull request #3
Opened 2017-09-03 03:29 UTC by memexcep

add fallback background color for home.css

2017-09-03 03:39 UTC, tianlunte commented on css/home.css
> +    background: linear-gradient(top, #373737, #212121);
这几个之间有什么区别？

2017-09-03 03:42 UTC, memexcep commented on css/home.css
> +    background: linear-gradient(top, #373737, #212121);
https://en.wikipedia.org/wiki/CSS_hack#Browser_prefixes
不同的浏览器，对这些还没完全成熟敲定的css属性实现方式略有差别。

2017-09-03 03:43 UTC, tianlunte requested changes
请➕上comment 以便后面的人查看

2017-09-03 03:52 UTC, tianlunte commented on css/home.css
> +    background: -webkit-linear-gradient(top, #373737, #212121);／＊Each of the most popular browser rendering engines has its own vendor-specific prefix for experimental properties.*/
the comments should be more specific, like -o-linear-gradient is for Opera 11.1 to 12.0, we should put comment for each of these variants

2017-09-04 06:26 UTC, nelzomal approved these changes

2017-09-04 06:26 UTC, nelzomal submitted a review, later dismissed

2017-09-05 01:49 UTC, tianlunte approved these changes

2017-09-05 01:50 UTC, merged